### ISSUE TITLE
生成するPDFファイルの様式をインボイス制度に準拠させる

### ISSUE THREAD

**Issue by mikkun** [mikkun/gnucash-util-jp#1]
## TODO

- [x] 作成者情報ファイル`company.txt`を改修
- [x] サンプルHTMLファイル`example-gnc3.html`を改修
- [x] プログラム本体`convert_invoice`を改修

## 参考リンク

[インボイス制度の概要｜国税庁](https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/invoice_about.htm)
